import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { campaigns, type CampaignDefinition, type PracticeChallengeDefinition } from "@kodergarden/shared";
import { countBlocks, validateProgram, type Program } from "@kodergarden/language";
import { executeProgram, GridRuntime, type ExecutionEvent, type GridSnapshot } from "@kodergarden/engine";
import { VisualEditor } from "../editor/VisualEditor.js";
import { commitHistory, createHistory, fromExecutableProgram, redoHistory, toExecutableProgram, undoHistory, type EditorProgram } from "../editor/model.js";
import { GridWorld } from "../GridWorld.js";
import { useI18n } from "../i18n.js";
import { applyExecutionEvent, initialPlaybackState, playbackDelay } from "../playback.js";
import { campaignChallengeUnlocked, loadCampaignProgress, recordCampaignRun, saveCampaignProgress, starsForRun, type CampaignProgress } from "./progress.js";

let identity=0;
const makeEditor=(source:Program):EditorProgram=>fromExecutableProgram(source,()=>`campaign-${identity++}`);
const wait=(ms:number,signal:AbortSignal):Promise<void>=>new Promise(resolve=>{const timer=window.setTimeout(resolve,ms);signal.addEventListener("abort",()=>{window.clearTimeout(timer);resolve();},{once:true});});
const advancedCampaigns=campaigns.filter(campaign=>campaign.kind==="advanced");
const stars=(count:number)=>`${"★".repeat(count)}${"☆".repeat(3-count)}`;

export function CampaignMode(){
 const {locale,setLocale,t}=useI18n();
 const [screen,setScreen]=useState<"library"|"path"|"challenge">("library");
 const [campaign,setCampaign]=useState<CampaignDefinition>(advancedCampaigns[0]!);
 const [challenge,setChallenge]=useState<PracticeChallengeDefinition>(advancedCampaigns[0]!.challenges[0]!);
 const [progress,setProgress]=useState<CampaignProgress>(loadCampaignProgress);
 const [history,setHistory]=useState(()=>createHistory(makeEditor(challenge.starter)));
 const [playback,setPlayback]=useState(()=>initialPlaybackState(new GridRuntime(challenge.world).snapshot()));
 const [speed,setSpeed]=useState(1); const [workbenchView,setWorkbenchView]=useState<"program"|"world">("program");
 const [outcome,setOutcome]=useState<{complete:boolean;stars:0|1|2|3;blocks:number;steps:number}|null>(null);
 const controller=useRef<AbortController|null>(null); const editor=history.present; const executable=useMemo(()=>toExecutableProgram(editor),[editor]); const running=playback.status==="running";
 const initial=useCallback(()=>new GridRuntime(challenge.world).snapshot(),[challenge]);
 const chooseCampaign=(next:CampaignDefinition)=>{setCampaign(next);setScreen("path");};
 const choose=(next:PracticeChallengeDefinition)=>{controller.current?.abort();setChallenge(next);setHistory(createHistory(makeEditor(next.starter)));setPlayback(initialPlaybackState(new GridRuntime(next.world).snapshot()));setOutcome(null);setWorkbenchView("program");setScreen("challenge");};
 const edit=(next:EditorProgram)=>{setHistory(current=>commitHistory(current,next));setOutcome(null);};
 const reset=useCallback(()=>{controller.current?.abort();controller.current=null;setPlayback(initialPlaybackState(initial()));setOutcome(null);},[initial]);
 useEffect(()=>()=>controller.current?.abort(),[]);
 const run=async()=>{if(controller.current)return;setWorkbenchView("world");reset();const valid=validateProgram(executable);if(!valid.ok)return;const blocks=countBlocks(valid.program);const result=executeProgram(valid.program,new GridRuntime(challenge.world));const control=new AbortController();controller.current=control;for(const event of result.events as readonly ExecutionEvent<GridSnapshot>[]){if(control.signal.aborted)break;setPlayback(state=>applyExecutionEvent(state,event));await wait(playbackDelay(event,speed),control.signal);}if(control.signal.aborted)return;controller.current=null;const rating=starsForRun(result.succeeded,blocks,result.executionSteps,challenge.parBlocks!,challenge.parSteps!);setOutcome({complete:result.succeeded,stars:rating,blocks,steps:result.executionSteps});if(rating>0){const earned=rating as 1|2|3;setProgress(current=>{const next=recordCampaignRun(current,campaign.id,challenge.id,blocks,result.executionSteps,earned);saveCampaignProgress(next);return next;});}};
 const nextChallenge=()=>{const next=campaign.challenges[challenge.order];if(next)choose(next);else setScreen("path");};
 const language=<select className="language-select" aria-label="Language" value={locale} onChange={e=>setLocale(e.target.value as "en"|"es")}><option value="en">{t("language.english")}</option><option value="es">{t("language.spanish")}</option></select>;
 if(screen==="library"){return <main><header className="site-header"><Brand/><div className="lab-label"><span>{t("campaign.mode")}</span><i/></div><div className="header-actions">{language}</div></header><section className="practice-hero"><span className="eyebrow"><i/>{t("campaign.mode")}</span><h1>{t("campaign.library.title")}</h1><p>{t("campaign.library.body")}</p></section><section className="campaign-library">{advancedCampaigns.map(item=>{const results=progress.campaigns[item.id]??{};const completed=Object.keys(results).length;const totalStars=Object.values(results).reduce((sum,result)=>sum+result.stars,0);return <button className="campaign-card" key={item.id} onClick={()=>chooseCampaign(item)}><span className="campaign-card-mark">✦</span><div><small>{t("campaign.label")} {item.order-1}</small><strong>{t(item.titleKey)}</strong><p>{t(item.descriptionKey)}</p><b>{t("campaign.summary",{done:completed,total:item.challenges.length,stars:totalStars,max:item.challenges.length*3})}</b></div><i>→</i></button>})}</section></main>}
 if(screen==="path"){const ids=campaign.challenges.map(item=>item.id);const results=progress.campaigns[campaign.id]??{};const completed=Object.keys(results).length;const totalStars=Object.values(results).reduce((sum,result)=>sum+result.stars,0);return <main><header className="site-header"><Brand/><button className="back-button" onClick={()=>setScreen("library")}>← {t("campaign.all")}</button><div className="header-actions">{language}</div></header><section className="practice-hero"><span className="eyebrow"><i/>{t("campaign.mode")}</span><h1>{t(campaign.titleKey)}</h1><p>{t(campaign.descriptionKey)}</p><strong>{t("campaign.summary",{done:completed,total:campaign.challenges.length,stars:totalStars,max:campaign.challenges.length*3})}</strong></section><section className="challenge-path">{campaign.challenges.map(item=>{const unlocked=campaignChallengeUnlocked(item.order,ids,progress,campaign.id);const result=results[item.id];return <button key={item.id} className={`challenge-card ${result?"is-done":""} ${!unlocked?"is-locked":""}`} disabled={!unlocked} onClick={()=>choose(item)}><span className="challenge-orb">{result?result.stars:String(item.order).padStart(2,"0")}</span><span className="challenge-card-copy"><small>{t(item.conceptKey)}</small><strong>{t(item.titleKey)}</strong><span>{unlocked?t(item.instructionKey):t("campaign.locked")}</span>{result&&<b className="star-rating">{stars(result.stars)} · {result.bestBlocks} {t("common.blocks")} · {result.bestSteps} {t("common.steps")}</b>}</span><i>→</i></button>})}</section></main>}
 return <main><header className="site-header"><Brand/><button className="back-button" onClick={()=>setScreen("path")}>← {t("common.back")}</button><div className="header-actions">{language}</div></header><section className="challenge-intro editor-intro"><div className="challenge-summary"><span className="challenge-progress">{t("practice.challenge")} {challenge.order} / {campaign.challenges.length}</span><span className="eyebrow"><i/>{t(challenge.conceptKey)}</span><h1>{t(challenge.titleKey)}</h1><p>{t(challenge.instructionKey)}</p></div><div className="target-banner"><b>{t("campaign.targets")}</b><span>≤ {challenge.parBlocks} {t("common.blocks")}</span><span>≤ {challenge.parSteps} {t("common.steps")}</span></div></section><div className="responsive-tabs"><button className={workbenchView==="program"?"is-active":""} onClick={()=>setWorkbenchView("program")}>{t("editor.route")}</button><button className={workbenchView==="world"?"is-active":""} onClick={()=>setWorkbenchView("world")}>{t("sim.title")}</button></div><section className={`editor-workspace show-${workbenchView}`}><VisualEditor program={editor} allowed={challenge.allowed} onChange={edit} activePath={playback.activePath} conditionResult={playback.conditionResult} disabled={running} onUndo={()=>setHistory(undoHistory)} onRedo={()=>setHistory(redoHistory)} canUndo={history.past.length>0} canRedo={history.future.length>0} onRestore={()=>edit(makeEditor(challenge.starter))}/><section className="simulation-panel editor-simulation"><div className="sim-heading"><div><div className="section-kicker">{t("campaign.workspace")}</div><h2>{t("sim.title")}</h2></div><div className="block-count"><strong>{countBlocks(executable)} / {challenge.parBlocks}</strong><span>{t("common.blocks")}</span></div></div><GridWorld world={challenge.world} playback={playback} hideStatus={outcome!==null}/>{outcome&&<div className={`challenge-feedback ${outcome.complete?"is-complete":""}`}><strong>{outcome.complete?`${stars(outcome.stars)} ${t(`campaign.result.${outcome.stars}`)}`:t("sim.incomplete")}</strong><span>{t("sim.metrics",{blocks:outcome.blocks,steps:outcome.steps})}</span>{outcome.complete&&<button onClick={nextChallenge}>{challenge.order<campaign.challenges.length?t("common.next"):t("common.continue")} →</button>}</div>}<div className="controls"><div className="speed-control"><span>{t("common.speed")}</span>{[.5,1,2].map(value=><button key={value} className={speed===value?"is-selected":""} onClick={()=>setSpeed(value)} disabled={running}>{value}×</button>)}</div><div className="run-controls"><button className="reset-button" onClick={reset}>↺ <span>{running?t("common.stop"):t("common.reset")}</span></button><button className="run-button" onClick={()=>void run()} disabled={running||editor.statements.length===0}>{running?t("common.running"):t("common.run")}<span>▶</span></button></div></div></section></section></main>;
}
function Brand(){return <a className="brand" href="#" aria-label="Kodergarden"><span className="brand-mark">K</span><span>Koder<strong>garden</strong></span></a>}
