import { useEffect, useState, type FormEvent } from "react";
import type { AdminCatalogResponseV1, AdminDraft, AdminDraftResponseV1, AdminSessionResponseV1, CampaignResponseV1, CatalogCampaignDefinition } from "@kodergarden/shared";

async function json<T>(response:Response):Promise<T>{if(!response.ok){const body=await response.json().catch(()=>null) as {message?:string}|null;throw new Error(body?.message??`Request failed (${response.status})`);}return response.json() as Promise<T>;}

export function AdminApp(){
 const [session,setSession]=useState<AdminSessionResponseV1|null>(null),[catalog,setCatalog]=useState<AdminCatalogResponseV1|null>(null),[loading,setLoading]=useState(true),[message,setMessage]=useState(""),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[busy,setBusy]=useState(false),[draft,setDraft]=useState<AdminDraft|null>(null),[preview,setPreview]=useState<CatalogCampaignDefinition|null>(null),[previewLocale,setPreviewLocale]=useState<"en"|"es">("en");
 const loadCatalog=async()=>setCatalog(await json<AdminCatalogResponseV1>(await fetch("/api/admin/catalog")));
 useEffect(()=>{void(async()=>{try{const current=await json<AdminSessionResponseV1>(await fetch("/api/admin/auth/session"));setSession(current);await loadCatalog();}catch{/* signed out */}finally{setLoading(false);}})();},[]);
 const mutate=async<T,>(url:string,method:string,body?:unknown)=>{if(!session)throw new Error("Session expired");return json<T>(await fetch(url,{method,headers:{"content-type":"application/json","x-kodergarden-csrf":session.csrfToken},...(body===undefined?{}:{body:JSON.stringify(body)})}));};
 const login=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setMessage("");try{const current=await json<AdminSessionResponseV1>(await fetch("/api/admin/auth/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email,password})}));setSession(current);setPassword("");setCatalog(await json<AdminCatalogResponseV1>(await fetch("/api/admin/catalog")));}catch(reason){setMessage(reason instanceof Error?reason.message:"Sign in failed");}finally{setBusy(false);}};
 const logout=async()=>{if(session)await fetch("/api/admin/auth/logout",{method:"POST",headers:{"x-kodergarden-csrf":session.csrfToken}});setSession(null);setCatalog(null);setDraft(null);};
 const openDraft=async(campaignId:string,draftId:string|null)=>{setBusy(true);setMessage("");try{const result=draftId?await json<AdminDraftResponseV1>(await fetch(`/api/admin/drafts/${draftId}`)):await mutate<AdminDraftResponseV1>(`/api/admin/campaigns/${campaignId}/drafts`,"POST");setDraft(result.draft);setPreview(null);await loadCatalog();}catch(reason){setMessage(reason instanceof Error?reason.message:"Unable to open draft");}finally{setBusy(false);}};
 const save=async()=>{if(!draft)return;setBusy(true);setMessage("");try{const result=await mutate<AdminDraftResponseV1>(`/api/admin/drafts/${draft.id}`,"PATCH",{order:draft.order,translations:draft.translations,challenges:draft.challenges});setDraft(result.draft);setMessage("Draft saved.");}catch(reason){setMessage(reason instanceof Error?reason.message:"Unable to save draft");}finally{setBusy(false);}};
 const showPreview=async(locale:"en"|"es")=>{if(!draft)return;setBusy(true);setMessage("");try{const saved=await mutate<AdminDraftResponseV1>(`/api/admin/drafts/${draft.id}`,"PATCH",{order:draft.order,translations:draft.translations,challenges:draft.challenges});setDraft(saved.draft);setPreviewLocale(locale);setPreview((await json<CampaignResponseV1>(await fetch(`/api/admin/drafts/${draft.id}/preview?locale=${locale}`))).campaign);}catch(reason){setMessage(reason instanceof Error?reason.message:"Unable to preview draft");}finally{setBusy(false);}};
 const publish=async()=>{if(!draft||!window.confirm(`Publish version ${draft.version}? Learners will immediately receive this revision.`))return;setBusy(true);setMessage("");try{await mutate<AdminDraftResponseV1>(`/api/admin/drafts/${draft.id}`,"PATCH",{order:draft.order,translations:draft.translations,challenges:draft.challenges});await mutate<CampaignResponseV1>(`/api/admin/drafts/${draft.id}/publish`,"POST");setDraft(null);setPreview(null);await loadCatalog();setMessage("Revision published successfully.");}catch(reason){setMessage(reason instanceof Error?reason.message:"Unable to publish");}finally{setBusy(false);}};
 const setCampaignCopy=(locale:"en"|"es",field:"title"|"description",value:string)=>setDraft(current=>current&&({...current,translations:{...current.translations,[locale]:{...current.translations[locale],[field]:value}}}));
 const setChallenge=(slug:string,locale:"en"|"es",field:"title"|"instruction"|"concept",value:string)=>setDraft(current=>current&&({...current,challenges:current.challenges.map(item=>item.slug===slug?{...item,translations:{...item.translations,[locale]:{...item.translations[locale],[field]:value}}}:item)}));
 if(loading)return <main className="admin-state"><p>Checking your admin session…</p></main>;
 if(!session)return <main className="admin-login"><section className="admin-login-card"><Brand/><small>TEAM ADMIN</small><h1>Welcome back</h1><p>Sign in to manage the curriculum.</p><form onSubmit={login}><label>Email<input type="email" autoComplete="username" required value={email} onChange={event=>setEmail(event.target.value)}/></label><label>Password<input type="password" autoComplete="current-password" required value={password} onChange={event=>setPassword(event.target.value)}/></label>{message&&<div className="admin-error" role="alert">{message}</div>}<button disabled={busy}>{busy?"Signing in…":"Sign in"}</button></form><a href="/">← Learner app</a></section></main>;
 return <main className="admin-shell"><header className="admin-header"><Brand/><div><span>{session.user.displayName}</span><small>{session.user.email}</small></div><button onClick={()=>void logout()}>Sign out</button></header><section className="admin-content">{message&&<div className={message.includes("success")||message.includes("saved")?"admin-notice":"admin-error"}>{message}</div>}{draft?<DraftEditor draft={draft} busy={busy} preview={preview} previewLocale={previewLocale} onBack={()=>{setDraft(null);setPreview(null);setMessage("");}} onSave={()=>void save()} onPublish={()=>void publish()} onPreview={locale=>void showPreview(locale)} setCampaignCopy={setCampaignCopy} setChallenge={setChallenge}/>:<><div className="admin-title"><div><small>CURRICULUM</small><h1>Campaigns</h1><p>Create an isolated draft, review both languages, then publish it atomically.</p></div><span>{catalog?.campaigns.length??0} campaigns</span></div><div className="admin-campaigns">{catalog?.campaigns.map(campaign=><article key={campaign.id}><div><small>{campaign.kind}</small><h2>{campaign.titleKey}</h2><p>{campaign.descriptionKey}</p></div><dl><div><dt>Challenges</dt><dd>{campaign.challengeCount}</dd></div><div><dt>Published</dt><dd>{campaign.revisionId.slice(0,8)}</dd></div><div><dt>Draft</dt><dd>{campaign.draftVersion?`v${campaign.draftVersion}`:"None"}</dd></div></dl><button className="admin-primary" disabled={busy} onClick={()=>void openDraft(campaign.id,campaign.draftRevisionId)}>{campaign.draftRevisionId?"Edit draft":"Create draft"}</button></article>)}</div></>}</section></main>;
}

function Brand(){return <div className="admin-brand"><span>K</span><strong>Koder<em>garden</em></strong></div>;}
function DraftEditor({draft,busy,preview,previewLocale,onBack,onSave,onPublish,onPreview,setCampaignCopy,setChallenge}:{draft:AdminDraft;busy:boolean;preview:CatalogCampaignDefinition|null;previewLocale:"en"|"es";onBack:()=>void;onSave:()=>void;onPublish:()=>void;onPreview:(locale:"en"|"es")=>void;setCampaignCopy:(locale:"en"|"es",field:"title"|"description",value:string)=>void;setChallenge:(slug:string,locale:"en"|"es",field:"title"|"instruction"|"concept",value:string)=>void}){return <div className="draft-editor"><div className="draft-toolbar"><button onClick={onBack}>← Campaigns</button><div><small>DRAFT VERSION {draft.version}</small><h1>{draft.campaignId}</h1></div><div className="draft-actions"><button disabled={busy} onClick={()=>onPreview("en")}>Preview EN</button><button disabled={busy} onClick={()=>onPreview("es")}>Preview ES</button><button className="admin-primary" disabled={busy} onClick={onSave}>Save draft</button><button className="admin-publish" disabled={busy} onClick={onPublish}>Publish</button></div></div>{preview&&<section className="draft-preview"><div><small>PRIVATE PREVIEW · {previewLocale.toUpperCase()}</small><h2>{preview.titleKey}</h2><p>{preview.descriptionKey}</p></div><ol>{preview.challenges.map(item=><li key={item.id}><strong>{item.titleKey}</strong><span>{item.instructionKey}</span></li>)}</ol></section>}<section className="draft-section"><h2>Campaign copy</h2><div className="draft-languages">{(["en","es"] as const).map(locale=><fieldset key={locale}><legend>{locale==="en"?"English":"Spanish"}</legend><label>Title<input value={draft.translations[locale].title} onChange={event=>setCampaignCopy(locale,"title",event.target.value)}/></label><label>Description<textarea rows={3} value={draft.translations[locale].description} onChange={event=>setCampaignCopy(locale,"description",event.target.value)}/></label></fieldset>)}</div></section><section className="draft-section"><h2>Challenges</h2><div className="draft-challenges">{draft.challenges.map(challenge=><details key={challenge.slug}><summary><span>{challenge.order}</span><strong>{challenge.translations.en.title}</strong><small>{challenge.slug}</small></summary><div className="draft-languages">{(["en","es"] as const).map(locale=><fieldset key={locale}><legend>{locale==="en"?"English":"Spanish"}</legend><label>Title<input value={challenge.translations[locale].title} onChange={event=>setChallenge(challenge.slug,locale,"title",event.target.value)}/></label><label>Concept<input value={challenge.translations[locale].concept} onChange={event=>setChallenge(challenge.slug,locale,"concept",event.target.value)}/></label><label>Instruction<textarea rows={4} value={challenge.translations[locale].instruction} onChange={event=>setChallenge(challenge.slug,locale,"instruction",event.target.value)}/></label></fieldset>)}</div></details>)}</div></section></div>;}
