import { validateProgram } from "@kodergarden/language";
import { commitHistory, createHistory, deleteStatement, elseContainerId, findLocation, fromExecutableProgram, insertStatement, moveStatement, redoHistory, thenContainerId, toExecutableProgram, undoHistory, updateCondition, updateRepeatCount, updateTurn, type EditorProgram } from "./model.js";

const assert = (condition: boolean, message: string): void => { if (!condition) throw new Error(message); };
const move = { id: "m", type: "moveForward" } as const;
const turn = { id: "t", type: "turn", direction: "right" } as const;
const repeat = { id: "r", type: "repeat", count: 3, body: [] } as const;
const conditional = { id: "if", type: "if", condition: "ahead", body: [] } as const;
let editor: EditorProgram = { statements: [] };
editor = insertStatement(editor, { containerId: null, index: 0 }, move);
assert(editor.statements[0]?.id === "m", "inserts at root");
editor = insertStatement(editor, { containerId: null, index: 1 }, repeat);
editor = insertStatement(editor, { containerId: "r", index: 0 }, turn);
assert(editor.statements[1]?.type === "repeat" && editor.statements[1].body[0]?.id === "t", "inserts inside repeat");
editor = moveStatement(editor, { containerId: null, index: 0 }, { containerId: "r", index: 1 });
assert(findLocation(editor, "m")?.containerId === "r", "moves root into repeat");
editor = moveStatement(editor, { containerId: "r", index: 0 }, { containerId: null, index: 0 });
assert(editor.statements[0]?.id === "t", "moves repeat child to root");
editor = insertStatement(editor, { containerId: null, index: 0 }, { id: "m2", type: "moveForward" });
editor = moveStatement(editor, { containerId: null, index: 0 }, { containerId: null, index: 2 });
assert(editor.statements[1]?.id === "m2", "reorders root statements");
editor = updateTurn(editor, "t", "left");
assert(editor.statements[0]?.type === "turn" && editor.statements[0].direction === "left", "changes turn direction");
editor = updateRepeatCount(editor, "r", 500);
const updatedRepeat = editor.statements.find((item) => item.id === "r");
assert(updatedRepeat?.type === "repeat" && updatedRepeat.count === 100, "clamps repeat count");
editor = deleteStatement(editor, "m2");
assert(!findLocation(editor, "m2"), "deletes a statement");
const executable = toExecutableProgram(editor);
assert(validateProgram(executable).ok, "generates a valid executable AST");
assert(JSON.stringify(executable).includes("turnLeft"), "maps editor turn to executable statement");
editor = insertStatement(editor, { containerId: null, index: 0 }, conditional);
assert(editor.statements[0]?.type === "if", "inserts If at root");
editor = insertStatement(editor, { containerId: "if", index: 0 }, { id: "if-move", type: "moveForward" });
assert(findLocation(editor, "if-move")?.containerId === "if", "inserts into If");
editor = moveStatement(editor, findLocation(editor, "t")!, { containerId: "if", index: 1 });
assert(findLocation(editor, "t")?.containerId === "if", "moves root into If");
editor = moveStatement(editor, findLocation(editor, "if")!, { containerId: "r", index: 0 });
assert(findLocation(editor, "if")?.containerId === "r", "nests If inside Repeat");
editor = moveStatement(editor, findLocation(editor, "if")!, { containerId: null, index: 0 });
editor = moveStatement(editor, findLocation(editor, "r")!, { containerId: "if", index: 0 });
assert(findLocation(editor, "r")?.containerId === "if", "nests Repeat inside If");
editor = moveStatement(editor, findLocation(editor, "m")!, { containerId: "if", index: 1 });
assert(findLocation(editor, "m")?.containerId === "if", "moves instructions between containers");
const nestedExecutable = toExecutableProgram(editor);
assert(validateProgram(nestedExecutable).ok && JSON.stringify(nestedExecutable).includes('"type":"if"'), "generates valid nested If AST");
editor = moveStatement(editor, findLocation(editor, "if")!, { containerId: null, index: editor.statements.length });
assert(findLocation(editor, "if")?.containerId === null, "moves If to root");
editor = deleteStatement(editor, "if");
assert(!findLocation(editor, "if"), "deletes If and its body");
const beforeIf = createHistory(editor);
const withIf = commitHistory(beforeIf, insertStatement(editor, { containerId: null, index: 0 }, conditional));
assert(findLocation(withIf.present, "if")?.containerId === null, "history commits If edits");
const undoneIf = undoHistory(withIf);
assert(!findLocation(undoneIf.present, "if"), "undo removes committed If");
const redoneIf = redoHistory(undoneIf);
assert(findLocation(redoneIf.present, "if")?.containerId === null, "redo restores committed If");
let ifElseEditor: EditorProgram = { statements: [{ id: "choice", type: "ifElse", condition: "ahead", thenBody: [], elseBody: [] }] };
ifElseEditor = insertStatement(ifElseEditor, { containerId: thenContainerId("choice"), index: 0 }, { id: "yes-move", type: "moveForward" });
ifElseEditor = insertStatement(ifElseEditor, { containerId: elseContainerId("choice"), index: 0 }, { id: "no-turn", type: "turn", direction: "left" });
assert(findLocation(ifElseEditor, "yes-move")?.containerId === thenContainerId("choice"), "finds instructions in the Then branch");
assert(findLocation(ifElseEditor, "no-turn")?.containerId === elseContainerId("choice"), "finds instructions in the Else branch");
const ifElseExecutable = toExecutableProgram(ifElseEditor);
assert(ifElseExecutable.version === 3 && validateProgram(ifElseExecutable).ok, "emits a valid version 3 program for If / Else");
const roundTrip = fromExecutableProgram(ifElseExecutable, (() => { let id = 0; return () => `round-${id++}`; })());
assert(roundTrip.statements[0]?.type === "ifElse" && roundTrip.statements[0].thenBody.length === 1 && roundTrip.statements[0].elseBody.length === 1, "round trips both If / Else branches");
ifElseEditor = updateCondition(ifElseEditor, "choice", "right");
assert(ifElseEditor.statements[0]?.type === "ifElse" && ifElseEditor.statements[0].condition === "right", "updates a condition dropdown");
const legacy = fromExecutableProgram({ version: 1, statements: [{ type: "if", condition: { type: "pathAhead" }, body: [] }] }, () => "legacy");
assert(legacy.statements[0]?.type === "if" && legacy.statements[0].condition === "ahead", "normalizes legacy Path Ahead conditions");
console.log("editor model: 29 tests passed");
