import { validateProgram } from "@kodergarden/language";
import { commitHistory, createHistory, deleteStatement, findLocation, insertStatement, moveStatement, redoHistory, toExecutableProgram, undoHistory, updateRepeatCount, updateTurn, type EditorProgram } from "./model.js";

const assert = (condition: boolean, message: string): void => { if (!condition) throw new Error(message); };
const move = { id: "m", type: "moveForward" } as const;
const turn = { id: "t", type: "turn", direction: "right" } as const;
const repeat = { id: "r", type: "repeat", count: 3, body: [] } as const;
const conditional = { id: "if", type: "ifPathAhead", body: [] } as const;
let editor: EditorProgram = { statements: [] };
editor = insertStatement(editor, { containerId: null, index: 0 }, move);
assert(editor.statements[0]?.id === "m", "inserts at root");
editor = insertStatement(editor, { containerId: null, index: 1 }, repeat);
editor = insertStatement(editor, { containerId: "r", index: 0 }, turn);
assert(editor.statements[1]?.type === "repeat" && editor.statements[1].body[0]?.id === "t", "inserts inside repeat");
editor = moveStatement(editor, { containerId: null, index: 0 }, { containerId: "r", index: 1 });
assert(findLocation(editor, "m")?.containerId === "r", "moves root into repeat");
editor = moveStatement(editor, { containerId: "r", index: 0 }, { containerId: null, index: 0 });
assert(editor.statements[0]?.id === "t", "moves repeat child to root");
editor = insertStatement(editor, { containerId: null, index: 0 }, { id: "m2", type: "moveForward" });
editor = moveStatement(editor, { containerId: null, index: 0 }, { containerId: null, index: 2 });
assert(editor.statements[1]?.id === "m2", "reorders root statements");
editor = updateTurn(editor, "t", "left");
assert(editor.statements[0]?.type === "turn" && editor.statements[0].direction === "left", "changes turn direction");
editor = updateRepeatCount(editor, "r", 500);
const updatedRepeat = editor.statements.find((item) => item.id === "r");
assert(updatedRepeat?.type === "repeat" && updatedRepeat.count === 100, "clamps repeat count");
editor = deleteStatement(editor, "m2");
assert(!findLocation(editor, "m2"), "deletes a statement");
const executable = toExecutableProgram(editor);
assert(validateProgram(executable).ok, "generates a valid executable AST");
assert(JSON.stringify(executable).includes("turnLeft"), "maps editor turn to executable statement");
editor = insertStatement(editor, { containerId: null, index: 0 }, conditional);
assert(editor.statements[0]?.type === "ifPathAhead", "inserts If at root");
editor = insertStatement(editor, { containerId: "if", index: 0 }, { id: "if-move", type: "moveForward" });
assert(findLocation(editor, "if-move")?.containerId === "if", "inserts into If");
editor = moveStatement(editor, findLocation(editor, "t")!, { containerId: "if", index: 1 });
assert(findLocation(editor, "t")?.containerId === "if", "moves root into If");
editor = moveStatement(editor, findLocation(editor, "if")!, { containerId: "r", index: 0 });
assert(findLocation(editor, "if")?.containerId === "r", "nests If inside Repeat");
editor = moveStatement(editor, findLocation(editor, "if")!, { containerId: null, index: 0 });
editor = moveStatement(editor, findLocation(editor, "r")!, { containerId: "if", index: 0 });
assert(findLocation(editor, "r")?.containerId === "if", "nests Repeat inside If");
editor = moveStatement(editor, findLocation(editor, "m")!, { containerId: "if", index: 1 });
assert(findLocation(editor, "m")?.containerId === "if", "moves instructions between containers");
const nestedExecutable = toExecutableProgram(editor);
assert(validateProgram(nestedExecutable).ok && JSON.stringify(nestedExecutable).includes('"type":"if"'), "generates valid nested If AST");
editor = moveStatement(editor, findLocation(editor, "if")!, { containerId: null, index: editor.statements.length });
assert(findLocation(editor, "if")?.containerId === null, "moves If to root");
editor = deleteStatement(editor, "if");
assert(!findLocation(editor, "if"), "deletes If and its body");
const beforeIf = createHistory(editor);
const withIf = commitHistory(beforeIf, insertStatement(editor, { containerId: null, index: 0 }, conditional));
assert(findLocation(withIf.present, "if")?.containerId === null, "history commits If edits");
const undoneIf = undoHistory(withIf);
assert(!findLocation(undoneIf.present, "if"), "undo removes committed If");
const redoneIf = redoHistory(undoneIf);
assert(findLocation(redoneIf.present, "if")?.containerId === null, "redo restores committed If");
console.log("editor model: 23 tests passed");
